# -*- coding: utf-8 -*-
"""FARAAZ AHMED - MAJOR PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cgnDqxIXN4TPeUmALbSz8HEj98K11Xh

Seasonal Agriculture Performance Analysis
Major Data Analytics Project
Domain: Agriculture **bold text**

Project Theme: Seasonal Agriculture Performance

Tools: Python, Pandas, NumPy, Matplotlib, Seaborn

Project Goal
Investigate how agricultural performance varies across seasons and identify meaningful patterns, trends, relationships and differences in the available data.

# 1. Problem Statement

Agricultural activities are influenced by seasonal variations in environmental conditions, farming practices, resource availability and economic conditions. As a result, agricultural performance may differ from one season to another.

The objective of this project is to analyze the given agricultural dataset and investigate seasonal differences in agricultural performance by identifying meaningful patterns, trends, relationships and variations within the available data.

Students should independently explore the dataset, formulate relevant analytical questions, select suitable analytical techniques and communicate findings based on evidence from the data.

#2. Project Objectives

* Understand the structure and quality of the agricultural dataset.
* Clean and prepare the data for analysis.
* Explore seasonal patterns in the dataset.
* Perform descriptive and statistical analysis.
* Investigate relationships among relevant variables.
* Compare agricultural performance across seasons and other meaningful groups.
* Use appropriate univariate, bivariate and multivariate visualizations.
* Identify significant findings from the data.
* Develop evidence-based insights and recommendations.

# 3. Dataset

The dataset contains farm-level agricultural records covering different seasons, locations, crops, environmental conditions, farming practices, production, costs, revenue, profit and resource usage.

**Dataset file:** `seasonal_agriculture_performance_dataset.csv`

The notebook is designed so that students can upload/place the CSV in the same folder as this notebook.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

file_path = "/content/seasonal_agriculture_performance_dataset.csv"
df = pd.read_csv(file_path)

print("Dataset loaded successfully.")

"""4. Initial Data Understanding"""

# Dataset shape

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head(5)

df.tail (5)

df.sample(5, random_state=42)

print(df.columns.tolist())

df.info()

df.describe()

df.describe(include="object")

"""5. Data Quality Analysis

Before performing analysis, investigate missing values, duplicates, data types and unusual values.
"""

missing = df.isnull().sum().sort_values(ascending=False)
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage.round(2)
})

missing_summary[missing_summary["Missing_Count"] > 0]

plt.figure(figsize=(12, 5))
missing_plot = missing[missing > 0]
if len(missing_plot) > 0:
    sns.barplot(x=missing_plot.index, y=missing_plot.values)
    plt.xticks(rotation=60, ha="right")
    plt.ylabel("Number of Missing Values")
    plt.xlabel("Column")
    plt.title("Missing Values by Column")
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found.")

duplicate_count=df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

df = df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

df.dtypes

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].nunique(), "unique values")
    print(df[col].dropna().unique()[:20])

df.isnull().sum().sort_values(ascending=False).head(10)

"""6. Feature / Variable Review

Review the available variables and classify them conceptually as:

* Identifier variables
* Categorical variables
* Numerical variables
* Environmental variables
* Operational variables
* Production/performance variables
* Economic variables
"""

numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(include="object").columns.tolist()

print("Numerical columns:")
print(numeric_columns)

print("\nCategorical columns:")
print(categorical_columns)

"""7. Statistical Analysis

Perform descriptive statistical analysis to understand the distribution and variation of the data.
"""

stats = df[numeric_columns].describe().T
stats["range"] = stats["max"] - stats["min"]
stats["IQR"] = stats["75%"] - stats["25%"]

stats

statistical_summary = pd.DataFrame({
    "Mean": df[numeric_columns].mean(),
    "Median": df[numeric_columns].median(),
    "Std_Dev": df[numeric_columns].std(),
    "Min": df[numeric_columns].min(),
    "Max": df[numeric_columns].max()
})

statistical_summary

season_summary = df.groupby("Season")[numeric_columns].agg(["mean", "median", "std"])
season_summary

"""8. Univerate Analysis

Create and interpret suitable plots for:

* Important categorical variables
* Important numerical variables
* Seasonal distribution
* Production/performance distributions
* Economic distributions

"""

plt.figure(figsize=(7, 5))
sns.countplot(data=df, x="Season")
plt.title("Distribution of Records by Season")
plt.xlabel("Season")
plt.ylabel("Number of Records")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x="Crop", order=df["Crop"].value_counts().index)
plt.xticks(rotation=45, ha="right")
plt.title("Distribution of Crops")
plt.xlabel("Crop")
plt.ylabel("Number of Records")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df, x="Yield_Tonnes_Ha", kde=True)
plt.title("Distribution of Agricultural Yield")
plt.xlabel("Yield (tonnes/ha)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df, x="Profit_INR", kde=True)
plt.title("Distribution of Farm Profit")
plt.xlabel("Profit (INR)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df, x="Rainfall_mm", kde=True)
plt.title("Distribution of Rainfall")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, y="Yield_Tonnes_Ha")
plt.title("Yield Distribution and Potential Outliers")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

"""9. Outlier Analysis

Investigate potential outliers using statistical and visual methods.

Student task: Do not automatically delete outliers. Decide whether an extreme value is:

* A data-entry problem,
* A legitimate observation,
* Or something requiring further investigation.

Univariate: Season distribution (Pie Chart)
"""

plt.figure(figsize=(7, 7))
df['Season'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, cmap='viridis')
plt.title('Distribution of Records by Season')
plt.ylabel('') # Hide the default 'Season' label on the y-axis
plt.tight_layout()
plt.show()

outlier_summary = []

for col in numeric_columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    count = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_summary.append({
        "Column": col,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": count,
        "Outlier_Percentage": round(count / len(df) * 100, 2)
    })

outlier_summary = pd.DataFrame(outlier_summary).sort_values(
    "Outlier_Count", ascending=False
)

outlier_summary

"""10. Bivariate Analysis

Bivariate analysis examines relationships or differences between two variables.

Students should investigate relationships that are relevant to the seasonal agriculture problem.


"""

# Bivariate: Season vs Yield

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="Season", y="Yield_Tonnes_Ha")
plt.title("Yield Distribution Across Seasons")
plt.xlabel("Season")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

"""Bar plots for Bivariate Analysis"""

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x="Season", y="Profit_INR", errorbar=None)
plt.title("Average Profit Across Seasons (Bar Plot)")
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")
plt.tight_layout()
plt.show()

#Bivariate: Season vs Water Usage

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="Season", y="Water_Used_m3")
plt.title("Water Usage Across Seasons")
plt.xlabel("Season")
plt.ylabel("Water Used (m³)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x="Season", y="Water_Used_m3", errorbar=None)
plt.title("Average Water Usage Across Seasons (Bar Plot)")
plt.xlabel("Season")
plt.ylabel("Average Water Used (m³)")
plt.tight_layout()
plt.show()

# Bivariate: Rainfall vs Yield

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="Rainfall_mm", y="Yield_Tonnes_Ha", alpha=0.5)
plt.title("Rainfall vs Agricultural Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

# Bivariate: Farm area vs Production

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="Farm_Area_Hectares", y="Production_Tonnes", alpha=0.5)
plt.title("Farm Area vs Production")
plt.xlabel("Farm Area (hectares)")
plt.ylabel("Production (tonnes)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
sns.barplot(data=df, x="Irrigation_Method", y="Yield_Tonnes_Ha", errorbar=None)
plt.title("Average Yield Across Irrigation Methods (Bar Plot)")
plt.xlabel("Irrigation Method")
plt.ylabel("Average Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

"""11. Multivariate Analysis

Multivariate analysis examines more than two variables together.

Use multivariate plots to investigate how season interacts with other dimensions such as crop type, resource usage or economic performance.


"""

# Multivariate: Season, crop and yield

plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="Crop", y="Yield_Tonnes_Ha", hue="Season")
plt.xticks(rotation=45, ha="right")
plt.title("Yield by Crop and Season")
plt.xlabel("Crop")
plt.ylabel("Yield (tonnes/ha)")
plt.legend(title="Season")
plt.tight_layout()
plt.show()

"""Multivariate: Grouped Bar Plot of Average Yield by Crop and Season"""



crop_season_summary = (
    df.groupby(["Season", "Crop"])
    .agg(
        Average_Yield=("Yield_Tonnes_Ha", "mean"),
        Average_Profit=("Profit_INR", "mean"),
        Average_Water_Efficiency=("Water_Efficiency_t_per_1000m3", "mean")
    )
    .round(2)
    .sort_values(["Season", "Average_Yield"], ascending=[True, False])
)

plt.figure(figsize=(14, 7))
sns.barplot(data=crop_season_summary.reset_index(), x='Crop', y='Average_Yield', hue='Season', palette='viridis')
plt.title('Average Yield by Crop and Season (Grouped Bar Plot)')
plt.xlabel('Crop')
plt.ylabel('Average Yield (tonnes/ha)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Season')
plt.tight_layout()
plt.show()

"""Multivariate: Pair Plot of Key Environmental and Performance Metrics by Season"""

selected_columns = ['Avg_Temperature_C', 'Rainfall_mm', 'Humidity_pct', 'Yield_Tonnes_Ha', 'Profit_INR', 'Season']
sns.pairplot(df[selected_columns], hue='Season', palette='viridis', plot_kws={'alpha': 0.6})
plt.suptitle('Pair Plot of Environmental and Performance Metrics by Season', y=1.02) # Adjust title position
plt.tight_layout()

# Multivariate: Season, irrigation and yield

plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="Irrigation_Method", y="Yield_Tonnes_Ha", hue="Season")
plt.title("Yield by Irrigation Method and Season")
plt.xlabel("Irrigation Method")
plt.ylabel("Yield (tonnes/ha)")
plt.legend(title="Season")
plt.tight_layout()
plt.show()

#Multivariate: Rainfall, yield and season


plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df,
    x="Rainfall_mm",
    y="Yield_Tonnes_Ha",
    hue="Season",
    size="Farm_Area_Hectares",
    sizes=(20, 100),
    alpha=0.65
)
plt.title("Rainfall, Yield and Seasonal Differences")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

# Multivariate: Profit, yield and season

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df,
    x="Yield_Tonnes_Ha",
    y="Profit_INR",
    hue="Season",
    size="Farm_Area_Hectares",
    sizes=(20, 100),
    alpha=0.65
)
plt.title("Yield, Profit and Seasonal Differences")
plt.xlabel("Yield (tonnes/ha)")
plt.ylabel("Profit (INR)")
plt.tight_layout()
plt.show()

# Correlation heatmap for numerical variables

plt.figure(figsize=(16, 12))
corr = df[numeric_columns].corr(numeric_only=True)

sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5
)

plt.title("Correlation Matrix of Numerical Variables")
plt.tight_layout()
plt.show()

"""12. Seasonal Comparison

We should now move from individual plots to structured comparisons.

Task :

We create suitable summary tables and visualizations to compare seasons across meaningful measures.

We do not assume that every variable needs to be compared. Select variables that help answer the project problem.
"""

# General seasonal summary

season_metrics = df.groupby("Season").agg(
    Records=("Farm_ID", "count"),
    Average_Yield=("Yield_Tonnes_Ha", "mean"),
    Total_Production=("Production_Tonnes", "sum"),
    Average_Profit=("Profit_INR", "mean"),
    Total_Profit=("Profit_INR", "sum"),
    Average_Water_Used=("Water_Used_m3", "mean")
).round(2)

season_metrics

# Compare crop performance within each season

crop_season_summary = (
    df.groupby(["Season", "Crop"])
    .agg(
        Average_Yield=("Yield_Tonnes_Ha", "mean"),
        Average_Profit=("Profit_INR", "mean"),
        Average_Water_Efficiency=("Water_Efficiency_t_per_1000m3", "mean")
    )
    .round(2)
    .sort_values(["Season", "Average_Yield"], ascending=[True, False])
)
crop_season_summary

"""13. Additional Student-Driven Analysis

This section is intentionally open-ended.

Students should add at least 3 additional analyses that are not already provided above.

Possible directions include:

* Regional differences
* Crop-specific seasonal patterns
* Resource usage
* Economic performance
* Environmental conditions
* Risk patterns
* Relationships discovered during exploration

The student must explain why each additional analysis is relevant to the project problem.



"""

# Student Analysis 1

#Regional differences
# Question:
# How do crop yield and profitability vary across different states or regions, and which state-crop combinations generate the highest overall output?

# Analysis:
regional_summary = (
    df.groupby(["State", "Crop"])
    .agg(
        Average_Yield=("Yield_Tonnes_Ha", "mean"),
        Average_Profit=("Profit_INR", "mean"),
        Total_Production=("Yield_Tonnes_Ha", "sum")
    )
    .round(2)
    .sort_values(["State", "Average_Profit"], ascending=[True, False])
)
regional_summary

# Visualization:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(
    data=regional_summary.reset_index(),
    x="State",
    y="Average_Profit",
    hue="Crop"
)
plt.title("Average Profitability by Crop Across States")
plt.xlabel("State")
plt.ylabel("Average Profit (INR)")
plt.legend(title="Crop", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# Interpretation:
# This analysis highlights spatial variations in crop yield and financial performance across states.
# Identifying regional disparities allows agricultural planners to reallocate farming infrastructure,
# target localized crop subsidies, and recommend optimal crop selections based on specific regional strengths.

# Student Analysis 2

# Resource usage
# Question:
# How efficiently are resources (water and fertilizer) utilized per tonne of crop yield across different crops, and which crops require the most resource management optimization?

# Analysis:
df["Water_per_Ton"] = df["Water_Used_m3"] / df["Yield_Tonnes_Ha"]
df["Fertilizer_per_Ton"] = df["Fertilizer_kg_ha"] / df["Yield_Tonnes_Ha"]

resource_usage_summary = (
    df.groupby("Crop")
    .agg(
        Avg_Water_per_Ton=("Water_per_Ton", "mean"),
        Avg_Fertilizer_per_Ton=("Fertilizer_per_Ton", "mean"),
        Avg_Total_Water=("Water_Used_m3", "mean"),
        Avg_Total_Fertilizer=("Fertilizer_kg_ha", "mean")
    )
    .round(2)
    .sort_values("Avg_Water_per_Ton", ascending=True)
)
resource_usage_summary

# Visualization:
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax1 = plt.subplots(figsize=(10, 5))

sns.barplot(
    data=resource_usage_summary.reset_index(),
    x="Crop",
    y="Avg_Water_per_Ton",
    color="skyblue",
    ax=ax1
)
ax1.set_ylabel("Average Water per Ton (m³)", color="blue")
ax1.set_title("Resource Intensity per Tonne of Yield by Crop")
plt.xticks(rotation=45)

ax2 = ax1.twinx()
sns.lineplot(
    data=resource_usage_summary.reset_index(),
    x="Crop",
    y="Avg_Fertilizer_per_Ton",
    color="darkgreen",
    marker="o",
    linewidth=2,
    ax=ax2
)
ax2.set_ylabel("Average Fertilizer per Ton (kg)", color="darkgreen")

plt.tight_layout()
plt.show()

# Interpretation:
# Lower values for resource consumption per tonne signify higher input efficiency. Measuring water
# and fertilizer intensity directly pinpoints wasteful agricultural practices, providing clear data
# to guide sustainable irrigation investments and precision fertilization programs.

#Student Analysis 3: Risk Patterns


# Question:
# How do yield volatility and financial loss rates vary across different crops, and which crops carry the highest operational risk for farmers?
risk_patterns_summary = (
    df.groupby("Crop")
    .agg(
        Mean_Yield=pd.NamedAgg(column="Yield_Tonnes_Ha", aggfunc="mean"),
        Yield_Std_Dev=pd.NamedAgg(column="Yield_Tonnes_Ha", aggfunc="std"),
        Loss_Frequency_Count=pd.NamedAgg(column="Profit_INR", aggfunc=lambda x: (x < 0).sum()),
        Loss_Rate_Pct=pd.NamedAgg(column="Profit_INR", aggfunc=lambda x: (x < 0).mean() * 100)
    )
)

# Coefficient of Variation (CV) measures relative risk/volatility
risk_patterns_summary["Yield_CV_%"] = (
    risk_patterns_summary["Yield_Std_Dev"] / risk_patterns_summary["Mean_Yield"]
) * 100

risk_patterns_summary = (
    risk_patterns_summary.drop(columns=["Yield_Std_Dev"])
    .round(2)
    .sort_values("Yield_CV_%", ascending=False)
)
risk_patterns_summary

# Visualization:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))
sns.barplot(
    data=risk_patterns_summary.reset_index(),
    x="Crop",
    y="Yield_CV_%",
    hue="Crop", # Assign x variable to hue
    palette="Reds_r",
    legend=False # Set legend to False to avoid redundant legend
)
plt.title("Crop Yield Volatility (Coefficient of Variation %)")
plt.xlabel("Crop")
plt.ylabel("Yield CV (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Interpretation:
# High Coefficient of Variation (Yield_CV_Pct) highlights crops with unpredictable production yields,
# while Loss_Rate_Pct pinpoints crops that frequently fail to turn a profit. Identifying these high-risk
# crops helps financial institutions, insurers, and agricultural planners set appropriate risk premiums
# and advise farmers on safer crop diversification strategies.

"""Insight 1 : How do crop yield and profitability vary across different states or regions, and which state-crop combinations generate the highest overall output?

1. Observation: Commercial cash crops (Sugarcane and Chilli) consistently generate vastly higher average profits (~₹600,000 to ₹1,000,000) across all states, whereas staple food grains (Maize, Rice, and Wheat) frequently record negative average profit margins.
2. Evidence: Grouped bar chart visualization for Regional Differences Analysis (`regional_summary`), showing tall positive bars for Sugarcane and Chilli alongside negative bars dipping below zero for Maize, Rice, and Wheat across Andhra Pradesh, Gujarat, Punjab, and other states.
3. Interpretation: Spatial market dynamics and high commercial valuation strongly favor cash crop cultivation, while staple food crops suffer from high production costs or low wholesale market prices that frequently exceed realized revenues.
4. Limitation: This finding does not prove that food grains are inherently unprofitable for every individual farmer, as government minimum support prices (MSP), local storage facilities, and post-harvest transport costs vary within state sub-regions.

Insight 2: How efficiently are resources (water and fertilizer) utilized per tonne of crop yield across different crops, and which crops require the most resource management optimization?

1. Observation: Sugarcane demonstrates the highest resource conversion efficiency (consuming under 1,000 m³ of water and ~10 kg of fertilizer per tonne), while Rice demands the highest water intensity (>7,000 m³/tonne) and Pulses require the peak fertilizer intensity (>250 kg/tonne).
2. Evidence: Dual-axis chart visualization for Resource Usage Efficiency (`resource_usage_summary`), showing the lowest sky-blue bar and dark-green line point for Sugarcane, the tallest blue bar for Rice, and the highest green peak for Pulses.
3. Interpretation : High biomass yields per hectare dilute Sugarcane's unit input intensity, whereas lower tonnage yields in crops like Pulses and Rice inflate their calculated resource consumption per output unit, requiring targeted precision input management.
4. Limitation: Measuring resource efficiency solely on a per-tonne basis does not account for absolute seasonal crop duration or natural environmental absorption (e.g., rainwater reliance vs. energy-intensive artificial irrigation).

Insight 3 : How do yield volatility and financial loss rates vary across different crops, and which crops carry the highest operational risk for farmers?

1. Observation: Yield volatility (`Yield_CV_%`) spans from a peak of over 50% for Chilli down to roughly 42% for Cotton, with crops like Rice, Pulses, and Groundnut clustering around 46%.
2. Evidence: Bar chart visualization for Risk Patterns (`risk_patterns_summary`), showing the tallest dark red bar for Chilli, a middle cluster of bars near 45–47%, and the lowest light bar for Cotton.
3. Interpretation: High-volatility crops like Chilli carry substantial production risk due to yield unpredictability, whereas lower-CV crops like Cotton offer relatively greater output stability across farming cycles.
4. Limitation: High yield volatility does not automatically mean higher financial loss rates (`Loss_Rate_Pct`), as high-volatility cash crops can command premium market prices that mitigate volume drops.

**15. Recommendations**

Based only on the evidence found in the dataset, provide practical and data-driven recommendations.

Recommendations should:

* Clearly connect to an observed finding.
* Avoid unsupported assumptions.
* Acknowledge important limitations.
* Focus on what the data can reasonably support.

Recommendation 1: Regional Crop Allocation & Subsidy Restructuring

Action: Reallocate regional agricultural subsidies and encourage farmers in low-performing states to transition land allocation toward high-value cash crops (Sugarcane and Chilli) while modernizing input supply chains for staple grains (Maize, Rice, and Wheat).
* Connection to Finding: Addresses Insight 1, which revealed that Sugarcane and Chilli yield substantial profits (~₹600,000 to ₹1,000,000) across all states, whereas staple food grains consistently produce negative average profit margins.
* Supported Data Boundary: Relies directly on state-level profitability aggregates (`regional_summary`) and avoids making speculative assumptions about individual farm-level overhead or unmeasured logistics costs.
* Limitation Acknowledgment: While high-value cash crops offer higher profit margins, recommendations must acknowledge that food security requirements and local Minimum Support Price (MSP) guarantees mean staple grain production cannot be entirely phased out.

Recommendation 2: Target Precision Resource Interventions by Input Intensity

Action: Deploy precision drip irrigation systems specifically for high-water-intensity crops like Rice and optimize chemical application protocols for high-fertilizer-intensity crops like Pulses to reduce per-tonne resource consumption.

* Connection to Finding: Directly addresses Insight 2, which demonstrated that Rice consumes over 7,000 m³ of water per tonne while Pulses demand over 250kg of fertilizer per tonne, compared to Sugarcane's low unit consumption.
* Supported Data Boundary: Grounded strictly in the calculated resource usage metrics (`Avg_Water_per_Ton` and `Avg_Fertilizer_per_Ton`) within `resource_usage_summary`.
* Limitation Acknowledgment: Recommendations focus on output efficiency and do not assume uniform adoption rates, as hardware capital costs, total growing season durations, and reliance on natural rainfall versus pumped groundwater vary across farming regions.

Recommendation 3: Tailored Agricultural Risk Mitigation & Insurance Indexing
* Action: Establish targeted crop insurance schemes and yield-stabilization support primarily for high-volatility crops like Chilli, while promoting mixed-cropping strategies alongside lower-volatility alternatives like Cotton to buffer operational risk.
* Connection to Finding: Directly aligns with Insight 3, which established that Chilli exhibits the highest yield volatility (CV > 50%), while Cotton provides the lowest production variation (~42%).
* Supported Data Boundary: Based strictly on the statistical Coefficient of Variation (`Yield_CV_%`) and profit loss metrics computed in `risk_patterns_summary`.
* Limitation Acknowledgment: While insurance and diversification mitigate production fluctuations, risk management frameworks must account for the fact that high-volatility cash crops can still achieve overall profitability through premium market prices during low-supply seasons.

**16. Conclusion**

This project analyzed the `seasonal_agriculture_performance_dataset` to understand how agricultural performance varies across seasons and to identify meaningful patterns, trends, and relationships. The dataset provided a rich source of farm-level records encompassing environmental conditions, farming practices, production, costs, revenue, and profit.

### Key Revelations and Patterns:

1.  Seasonal Impact on Profitability: The analysis clearly showed significant seasonal variations in agricultural performance, particularly in terms of profitability. The Kharif season consistently demonstrated the highest average profits, followed by Rabi, while the Zaid season often resulted in negative average profits. This highlights the critical role of seasonal conditions in determining economic outcomes for farmers.

2.  Crop-Specific Seasonal Performance: Certain crops perform better in specific seasons. Sugarcane, for instance, showed exceptionally high yields and profits across all seasons, but its average yield was highest in Kharif. Conversely, staple crops like Maize, Rice, and Wheat frequently experienced negative profit margins, suggesting they are less profitable under current conditions.

3.  Environmental Factors and Yield: Environmental variables like rainfall and temperature are crucial determinants of yield. While there is a positive correlation between rainfall and yield, other factors also play a significant role, as indicated by the scatter plots. Different irrigation methods also showed varying average yields.

4.  Resource Utilization Efficiency: There are considerable differences in resource efficiency across crops. Sugarcane demonstrated high water and fertilizer efficiency per tonne of yield due to its high biomass production, whereas crops like Rice and Pulses exhibited lower efficiencies, consuming more resources per unit of output.

5.  Regional Disparities: Crop profitability and yield vary significantly across different states. Cash crops like Sugarcane and Chilli often yield higher profits across various regions, while staple grains struggle to be profitable, reinforcing the need for region-specific agricultural strategies.

6.  Yield Volatility and Risk: Crops exhibit different levels of yield volatility. Chilli was identified as a high-volatility crop, indicating unpredictable production, while cotton showed greater stability. This insight is crucial for risk management and crop insurance strategies.

### Useful Analytical Findings:

*   Identification of High-Value Crops: Sugarcane and Chilli stand out as high-profit crops, suggesting potential for increased focus in suitable regions.
*   Resource Management Hotspots : Rice (high water usage) and Pulses (high fertilizer usage) were identified as areas requiring optimized resource management interventions to improve efficiency.
*   Risk Assessment for Farmers: The quantification of yield volatility provides a basis for farmers, insurers, and policymakers to assess and mitigate agricultural risks more effectively.
*   Season-Specific Strategies: The data supports tailoring crop selection, resource allocation, and support programs based on seasonal characteristics to maximize profitability and minimize losses.

### Important Limitations of the Analysis:

*   Missing Data Imputation: Missing values in Rainfall, Soil Moisture, and Yield were not explicitly addressed with advanced imputation techniques, which could slightly impact the accuracy of analyses involving these variables.
*   Outlier Handling: While outliers were identified, no specific treatment (e.g., capping, transformation) was applied, assuming they are legitimate extreme observations. This might skew some statistical measures and visual representations.
*   Causation vs. Correlation: The analysis primarily focused on identifying correlations and patterns. Establishing definitive causal relationships would require more controlled experiments or advanced statistical modeling.
*   Lack of Time-Series Data: Without specific time-series data (e.g., year-over-year performance), it's challenging to assess long-term trends or the impact of climate change over time.
*   Generalization:** Findings are based on the provided dataset and may not be universally generalizable to all agricultural contexts within India or globally without further validation.

### Support for Future Investigation or Decision-Making:

This analysis lays a strong foundation for data-driven decision-making in the agricultural sector. Future investigations could involve:

*   Predictive Modeling: Developing models to predict optimal crop choices, yields, and profits based on seasonal forecasts and resource availability.
*   **Economic Impact Assessment: Deeper dives into the economic factors driving profitability differences, including market demand, government policies, and supply chain efficiencies.
*   Environmental Optimization: Research into sustainable farming practices, precise irrigation techniques, and organic fertilization methods to improve resource efficiency further.
*   Risk Management Tools: Creating more sophisticated risk assessment tools and insurance products tailored to specific crops, regions, and seasonal volatilities.
*   Policy Recommendations: Informing agricultural policy decisions regarding subsidies, crop diversification, and environmental protection based on empirical evidence from data.

By understanding these patterns and relationships, stakeholders can make more informed decisions to enhance agricultural sustainability, profitability, and food security.

17. Project Checklist

Before submission, confirm that your notebook includes:

- [x] Dataset loaded successfully
- [x] Top 5 rows analyzed
- [x] Dataset shape and structure examined
- [x] Data types examined
- [x] Missing values identified and handled
- [x] Duplicate records identified and handled
- [x] Descriptive/statistical analysis performed
- [x] Outliers investigated
- [x] Univariate analysis completed
- [x] Bivariate analysis completed
- [x] Multivariate analysis completed
- [x] Correlation analysis completed
- [x] Seasonal comparisons performed
- [x] At least 3 student-designed analyses completed
- [x] At least 8 meaningful insights documented
- [x] Evidence-based recommendations provided
- [x] Limitations discussed
- [x] Final conclusion provided
"""